import { Box, Settings, Shield, Users, Zap } from "lucide-react";

const slugs = [
	"stellar",
	"bitcoinsv",
	"ethereum",
	"dogecoin",
	"solana",
	"coinmarketcap",
	"coinbase",
	"chainlink",
	"hedera",
	"foundryvirtualtabletop",
	"blockchaindotcom",
	"stellar",
	"bitcoinsv",
	"ethereum",
	"dogecoin",
	"solana",
	"coinmarketcap",
	"coinbase",
	"chainlink",
	"hedera",
	"foundryvirtualtabletop",
	"blockchaindotcom",
	"stellar",
	"bitcoinsv",
	"ethereum",
	"dogecoin",
	"solana",
	"coinmarketcap",
	"coinbase",
	"chainlink",
	"hedera",
	"foundryvirtualtabletop",
	"blockchaindotcom",
	"stellar",
	"bitcoinsv",
	"ethereum",
	"dogecoin",
	"solana",
	"coinmarketcap",
	"coinbase",
	"chainlink",
	"hedera",
	"foundryvirtualtabletop",
	"blockchaindotcom",
	"stellar",
	"bitcoinsv",
	"ethereum",
	"dogecoin",
	"solana",
	"coinmarketcap",
	"coinbase",
	"chainlink",
	"hedera",
	"foundryvirtualtabletop",
	"blockchaindotcom",
	"stellar",
	"bitcoinsv",
	"ethereum",
	"dogecoin",
	"solana",
	"coinmarketcap",
	"coinbase",
	"chainlink",
	"hedera",
	"foundryvirtualtabletop",
	"blockchaindotcom",
];

const reviews = [
	{
		name: "Jack",
		username: "@jack",
		body: "I've never seen anything like this before. It's amazing. I love it.",
		img: "https://avatar.vercel.sh/jack",
	},
	{
		name: "Jill",
		username: "@jill",
		body: "I don't know what to say. I'm speechless. This is amazing.",
		img: "https://avatar.vercel.sh/jill",
	},
	{
		name: "John",
		username: "@john",
		body: "I'm at a loss for words. This is amazing. I love it.",
		img: "https://avatar.vercel.sh/john",
	},
	{
		name: "Jane",
		username: "@jane",
		body: "I'm at a loss for words. This is amazing. I love it.",
		img: "https://avatar.vercel.sh/jane",
	},
	{
		name: "Jenny",
		username: "@jenny",
		body: "I'm at a loss for words. This is amazing. I love it.",
		img: "https://avatar.vercel.sh/jenny",
	},
	{
		name: "James",
		username: "@james",
		body: "I'm at a loss for words. This is amazing. I love it.",
		img: "https://avatar.vercel.sh/james",
	},
];

const features = [
	{
		title: "Efficient",
		description: "Optimize your workflow with our powerful tools and features.",
		icon: Zap,
	},
	{
		title: "Customizable",
		description:
			"Tailor the platform to match your specific needs and preferences.",
		icon: Settings,
	},
	{
		title: "Scalable",
		description:
			"Grow your business without worrying about infrastructure limitations.",
		icon: Box,
	},
	{
		title: "Network Effects",
		description: "Benefit from a growing ecosystem of users and integrations.",
		icon: Users,
	},
	{
		title: "Secure",
		description: "Enterprise-grade security to protect your valuable data.",
		icon: Shield,
	},
	{
		title: "Privacy-First",
		description: "Your data remains yours with our privacy-focused approach.",
		icon: Lock,
	},
];

export { slugs, features, reviews };
